language: java
sudo: false

addons:
  apt:
    packages:
      - gdb

# keep gradle cache.
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

matrix:
  fast_finish: true
  include:
    # Ubuntu Linux (trusty) / Java 8 / Headed
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    # Ubuntu Linux (trusty) / Java 8 / Headless
    - os: linux
      dist: trusty
      jdk: oraclejdk8
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
      addons:
        apt:
          packages:
            - oracle-java8-installer
    # Ubuntu Linux (trusty) / Java 9 / Headed
    - os: linux
      dist: trusty
      jdk: oraclejdk9
      env:
        - _JAVA_OPTIONS="--add-opens=java.base/java.util=ALL-UNNAMED --add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED"
      addons:
        apt:
          packages:
            - oracle-java9-installer
    # Ubuntu Linux (trusty) / Java 9 / Headless
    - os: linux
      dist: trusty
      jdk: oraclejdk9
      env:
        - _JAVA_OPTIONS="--add-opens=java.base/java.util=ALL-UNNAMED --add-exports=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
      addons:
        apt:
          packages:
            - oracle-java9-installer
    # macOS / Java 8 / Headless
    - os: osx
      osx_image: xcode9
      env:
        - TRAVIS_JAVA_VERSION="8"
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
    # macOS / Java 9 / Headless
    - os: osx
      osx_image: xcode9
      env:
        - TRAVIS_JAVA_VERSION="9"
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
    # It is not currently possible to run JavaFX in headed mode on Travis CI
    # with the OpenGL ES graphics pipeline. While it is possible to run with
    # "-Dprism.order=sw" this "partial headless" testing scenario does not
    # provide any useful information.

before_script:
  - echo $HOME
  - echo $JAVA_OPTS
  - echo $GRADLE_OPTS
  # run on xvfb screen (for linux).
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start; fi

before_install: .ci/before_install.sh

# skip install stage.
install: true

# run gradle build.
script: .ci/script.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2532276e31bee9ba82b7
    on_success: change
    on_failure: always
