version: "{branch} {build}"

environment:
  matrix:
    - JAVA_VERSION: "8"
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0

    - JAVA_VERSION: "8"
      JAVA_OPTS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0

    - JAVA_VERSION: "9"
      JAVA_HOME: C:\jdk9

    - JAVA_VERSION: "9"
      JAVA_OPTS: "-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"
      JAVA_HOME: C:\jdk9

shallow_clone: true

build:
  verbosity: detailed

build_script:
  - ps: |
      if ($env:JAVA_VERSION -eq "9") {
        choco install jdk9 --version 9.0.1.11 -params 'installdir=C:\\jdk9'
        refreshenv
      }
  - cmd: |
      java -version
      gradlew --version --no-daemon
      gradlew versions build --info --no-daemon

test_script:
  - gradlew check --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper -> .gradle-wrapper\gradle-wrapper.properties

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2532276e31bee9ba82b7
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true

